<a href="https://colab.research.google.com/github/bearhz/pytorch_basic/blob/master/02_%E6%95%B0%E6%8D%AE%E7%94%9F%E6%88%90.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pytorch生成数据

In [ ]:
import torch

## 1. 生成1矩阵

In [ ]:
torch.ones([2,3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## 2. 生成0矩阵

In [ ]:
torch.zeros([3,3])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## 3. 生成0~1随机数矩阵

In [ ]:
torch.rand([3,4])

tensor([[0.9877, 0.5716, 0.6056, 0.6353],
        [0.4351, 0.7631, 0.7285, 0.6631],
        [0.6200, 0.5568, 0.7086, 0.7079]])

## 4. 生成0~5的整数矩阵

In [ ]:
torch.randint(0,5,(2,3))

tensor([[3, 4, 3],
        [2, 2, 3]])

## 5. 生成正态分布数据

In [ ]:
a = torch.normal(mean=0., std = 1., size=(3,4))
a

tensor([[ 0.6890,  0.1294,  0.6644,  1.3197],
        [-0.3216, -1.2029,  1.7503, -0.9781],
        [ 0.2967, -0.1055,  0.7516, -0.9255]])

In [ ]:
a.mean()

tensor(0.1723)

## 6. 模仿a生成一个b

In [ ]:
b = torch.rand_like(a)
b

tensor([[0.7209, 0.4610, 0.3774, 0.2056],
        [0.1966, 0.1070, 0.4203, 0.9536],
        [0.5891, 0.4073, 0.2548, 0.7567]])

In [ ]:
print(b.shape)
print(b.size())

torch.Size([3, 4])
torch.Size([3, 4])


## 7. 修改tensor的形状

In [ ]:
b.view(12)

tensor([0.7209, 0.4610, 0.3774, 0.2056, 0.1966, 0.1070, 0.4203, 0.9536, 0.5891,
        0.4073, 0.2548, 0.7567])

In [ ]:
b.reshape(4,3)

tensor([[0.7209, 0.4610, 0.3774],
        [0.2056, 0.1966, 0.1070],
        [0.4203, 0.9536, 0.5891],
        [0.4073, 0.2548, 0.7567]])

## 8. 获取tensor的数值

In [ ]:
b[1,1]

tensor(0.1070)

In [ ]:
b[1,1].dtype

torch.float32

In [ ]:
b[1,1].item()

0.10696911811828613

## 9. 把tensor和numpy array之间的转换

In [ ]:
import numpy as np
c = np.array(b)
c

array([[0.72086823, 0.46100795, 0.37735063, 0.20562375],
       [0.19660407, 0.10696912, 0.42030942, 0.953581  ],
       [0.5890683 , 0.4072765 , 0.25481904, 0.7567271 ]], dtype=float32)

In [ ]:
d = torch.tensor(c)
d, d.dtype

(tensor([[0.7209, 0.4610, 0.3774, 0.2056],
         [0.1966, 0.1070, 0.4203, 0.9536],
         [0.5891, 0.4073, 0.2548, 0.7567]]),
 torch.float32)