<a href="https://colab.research.google.com/github/bearhz/pytorch_basic/blob/master/03_pytorch%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pytorch tensor的基本运算操作

In [ ]:
import torch

In [ ]:
a = torch.randint(1,5,(2,3))
b = torch.randint(2,10,(2,3))
print(a)
print(b)

tensor([[4, 1, 3],
        [3, 2, 4]])
tensor([[5, 4, 8],
        [3, 7, 6]])


## 1. 加法

In [ ]:
a+b

tensor([[ 9,  5, 11],
        [ 6,  9, 10]])

In [ ]:
torch.add(a,b)

tensor([[ 9,  5, 11],
        [ 6,  9, 10]])

**修改自己的值**

In [ ]:
a.add_(b)
a

tensor([[ 9,  5, 11],
        [ 6,  9, 10]])

## 2. 减法

In [ ]:
a - b

tensor([[4, 1, 3],
        [3, 2, 4]])

In [ ]:
a

tensor([[ 9,  5, 11],
        [ 6,  9, 10]])

In [ ]:
a.sub_(b)

tensor([[4, 1, 3],
        [3, 2, 4]])

## 3. 乘法 除法 取余数

In [ ]:
print(a, a.dtype)
print(b, b.dtype)

tensor([[4, 1, 3],
        [3, 2, 4]]) torch.int64
tensor([[5, 4, 8],
        [3, 7, 6]]) torch.int64


In [ ]:
a * b

tensor([[20,  4, 24],
        [ 9, 14, 24]])

In [ ]:
a / b

tensor([[0.8000, 0.2500, 0.3750],
        [1.0000, 0.2857, 0.6667]])

In [ ]:
# 取余数
a % b

tensor([[4, 1, 3],
        [0, 2, 4]])

In [ ]:
# 除法取整
a // b

tensor([[0, 0, 0],
        [1, 0, 0]])

## 4. 矩阵乘法

In [ ]:
a

tensor([[4, 1, 3],
        [3, 2, 4]])

In [ ]:
b = torch.ones(3, 5).long()
b

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [ ]:
torch.matmul(a,b)

tensor([[8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9]])

## 5.矩阵的转置

In [ ]:
print(a)
a.T

tensor([[4, 1, 3],
        [3, 2, 4]])


tensor([[4, 3],
        [1, 2],
        [3, 4]])

## 6. 矩阵求和

In [ ]:
a

tensor([[4, 1, 3],
        [3, 2, 4]])

In [ ]:
a.sum()

tensor(17)

In [ ]:
a.sum(axis=0)

tensor([7, 3, 7])

In [ ]:
a.sum(axis=1)

tensor([8, 9])

## 7. 矩阵找最值

In [ ]:
a = torch.rand(3,4)
a

tensor([[0.2391, 0.1468, 0.9453, 0.6672],
        [0.0469, 0.6806, 0.1603, 0.8650],
        [0.8506, 0.2688, 0.5522, 0.4265]])

In [ ]:
torch.min(a)

tensor(0.0469)

In [ ]:
torch.max(a)

tensor(0.9453)

In [ ]:
# 找索引
torch.argmin(a)

tensor(4)

In [ ]:
torch.argmax(a)

tensor(2)

## 8. 平均值和中位数

In [ ]:
a.mean()

tensor(0.4874)

In [ ]:
a.mean(axis=0)

tensor([0.3789, 0.3654, 0.5526, 0.6529])

In [ ]:
a.mean(axis = 1)

tensor([0.4996, 0.4382, 0.5245])

In [ ]:
c = a.view(12)
print(a)
median_value, median_index = c.median(dim = 0)
print(f"median_value={median_value}, median_index={median_index}")

tensor([[0.2391, 0.1468, 0.9453, 0.6672],
        [0.0469, 0.6806, 0.1603, 0.8650],
        [0.8506, 0.2688, 0.5522, 0.4265]])
median_value=0.4264528751373291, median_index=11


In [ ]:
median_value, median_index = a.median(dim = 0)
print(f"dim 0: median_value={median_value}, median_index={median_index}")
median_value, median_index = a.median(dim = 1)
print(f"dim 1: median_value={median_value}, median_index={median_index}")

dim 0: median_value=tensor([0.2391, 0.2688, 0.5522, 0.6672]), median_index=tensor([0, 2, 2, 0])
dim 1: median_value=tensor([0.2391, 0.1603, 0.4265]), median_index=tensor([0, 2, 3])


## 9. 开平方 求平方

In [ ]:
a = torch.randint(1,9,(2,3))
a

tensor([[3, 5, 5],
        [1, 4, 8]])

In [ ]:
a.sqrt()

tensor([[1.7321, 2.2361, 2.2361],
        [1.0000, 2.0000, 2.8284]])

In [ ]:
a ** 2

tensor([[ 9, 25, 25],
        [ 1, 16, 64]])