<a href="https://colab.research.google.com/github/bearhz/pytorch_basic/blob/master/04_%E6%95%B0%E6%8D%AE%E7%9A%84%E7%B4%A2%E5%BC%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 索引

In [ ]:
import torch

## 1. 一维

In [ ]:
a = torch.arange(0, 10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:4]

tensor([2, 3])

In [ ]:
a[2:-1]

tensor([2, 3, 4, 5, 6, 7, 8])

In [ ]:
a[2:]

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[-3:]

tensor([7, 8, 9])

In [ ]:
a[:4]

tensor([0, 1, 2, 3])

In [ ]:
index = [1, 3, 3, 5]
a[index]

tensor([1, 3, 3, 5])

## 2. 多维

In [ ]:
a = torch.randint(0, 5, (3, 4))
a

tensor([[1, 2, 2, 0],
        [3, 0, 1, 0],
        [0, 2, 4, 2]])

In [ ]:
a[:-1,1:-1]

tensor([[2, 2],
        [0, 1]])

In [ ]:
index = [[0,1,2,2],[0,1,2,2]]
a[index]

tensor([1, 0, 4, 4])